# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Kav's Blog'
tagline:          'Front end developer with a special interest in user research'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Kav Khalsa'
  url:            https://twitter.com/koolkav1

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:          https://github.com/koolkav1/koolkav1.github.io
